#!/usr/bin/with-contenv sh

if [ "$NGINX_ENABLE_DEV" = true ]; then
    sed -i 's/<NGINX_ENV>/(app|app_dev|config)/' /etc/nginx/conf.d/default.conf
else
    sed -i 's/<NGINX_ENV>/app/' /etc/nginx/conf.d/default.conf
fi

if [ "$PHP_XDEBUG" = true ]; then
    php5enmod xdebug
else
    php5dismod xdebug
fi

rm -rf /srv/app/cache/*
chown -R www-data: /srv/app/cache > /dev/null 2>&1
chown -R www-data: /srv/app/logs > /dev/null 2>&1
